---
title: "Maruia Trap-lines: Monthly Catch by Location"
author: "Peter Alspach"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    pdf_document:
  # html_document:
  # html_notebook:
    theme: spacelab
    toc: yes
    toc_depth: 5
    # toc_float: yes
    # code_folding: hide
---

<!-- To do: -->
<!-- Mammals are defined at the end of the 'getReady' chunk (about line 58) -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, cache=FALSE, error=TRUE)
library(knitr)
```

```{r readData}
# Set the working directory and read the data
setwd('~/GitHub/SpringsJunction/TrapLines')
load('TrapCoordinates.RData') # Waypoints (saved by TrapLocations.Rmd)

# Get current and previous years's data
tl <- read.csv('TrapCatches.csv', header=TRUE, sep=',', stringsAsFactors=FALSE)
tl18 <- read.csv('TrapCatches2018.csv', header=TRUE, sep=',', stringsAsFactors=FALSE)

# Remove time from date stamp
tl$Date.Checked <- substring(tl$Date.Checked, 1, 10)
tl$jDay <- julian.Date(as.Date(tl$Date.Checked), origin=as.Date('2018-12-31')) # manually change
tl18$Date.Checked <- substring(tl18$Date.Checked, 1, 10)
tl18$jDay <- julian.Date(as.Date(tl18$Date.Checked), origin=as.Date('2018-12-31')) # manually change

tlAll <- rbind(tl18, tl)
tl12m <- tlAll[tlAll$Date.Checked > Sys.Date()-366,] # 12 months data
lID <- unique(tl12m$Line)

# Rename traps with only a single digit 'd' to '0d'
relNo <- tl12m[grep('[[:upper:]][[:digit:]]{1}$', tl12m$Tag.No), 'Tag.No']
relNo <- paste0(substring(relNo, 1, nchar(relNo)-1), '0', substring(relNo, nchar(relNo)))
tl12m[grep('[[:upper:]][[:digit:]]{1}$', tl12m$Tag.No), 'Tag.No'] <- relNo
```

```{r getReady}
# Set the cut-off dates for the monthly intervals
lastDate <- sort(tl12m$Date.Checked, decreasing=TRUE)[1]
yr <- as.integer(substring(lastDate, 1, 4))
mth <- as.integer(substring(lastDate, 6, 7))
cutDays <- paste(yr, c(paste0('0', 1:9), 10:12), '15', sep='-') # cut at the middle of the month 
cutDays <- julian.Date(as.Date(cutDays), origin=as.Date(paste0(yr-1, '-12-31')))
obsMth <- cut(tl12m$jDay, c(cutDays, 365+15+floor((4.001-yr%%4)/4)), 
              labels=c('J-F', 'F-M', 'M-A','A-M', 'M-J', 'J-J',
                       'J-A', 'A-S', 'S-O', 'O-N', 'N-D', 'D-J'))

# Set the standard trap status of interest
stdStat <- c('Sprung and Empty','Rat','Stoat','Weasel') # standard trap status
allMammals <- c('Rat','Stoat','Weasel','Cat','Ferret','Mouse','Rabbit','Hedgehog','Hare','Possum')
```

```{r mthCatchP}
# First tabulate the number of pests caught
trap1 <- table(obsMth, tl12m$Tag.No, tl12m$Trap.1)
trap2 <- table(obsMth, tl12m$Tag.No, tl12m$Trap.2)
trap2 <- trap2[, , dimnames(trap2)[[3]]!='N/A']
tt <- unique(c(dimnames(trap1)[[3]], dimnames(trap2)[[3]]))
# Append to trap1 if necessary
appd <- array(0, replace(dim(trap1), 3, length(tt)-dim(trap1)[3]),
              dimnames=list(dimnames(trap1)[[1]], dimnames(trap1)[[2]],
                            tt[!(tt %in% dimnames(trap1)[[3]])]))
trap1 <- abind::abind(trap1, appd, along=3)
# Append to trap2
appd <- array(0, replace(dim(trap2), 3, length(tt)-dim(trap2)[3]),
              dimnames=list(dimnames(trap2)[[1]], dimnames(trap2)[[2]],
                            tt[!(tt %in% dimnames(trap2)[[3]])]))
trap2 <- abind::abind(trap2, appd, along=3)
# Only interested in mammalian catch
mammals <- allMammals[allMammals %in% dimnames(trap1)[[3]]]
trap1 <- apply(trap1[,, mammals], 1:2, sum)
trap2 <- apply(trap2[,, mammals], 1:2, sum)

catch <- trap1 + trap2
catch[table(obsMth, tl12m$Line)==0] <- NA # put missing value in where line not checked
catch <- catch[apply(catch, 1, function(x) length(x[!is.na(x)]))!=0,] # remove unchecked months
catch <- 100*catch/matrix(nTrap, nrow(catch), ncol(catch), byrow=TRUE) # per trap

```
