---
title: "Tramp Diaries 1986-1995"
author: "Peter Alspach"
date: "12/08/2019"
output: pdf_document
---


## Wangapeka (December 1986)
### Peter Van Essen and me

__05 December__:  
Left Rolling River carpark around 10:00 in fine weather.  Initial vegetation scrubby - probably reverted after early attempts at farming.  Passed Stoney Creek, then a little while further Kiwi Stream.  Previous to this (after about 1$\frac{1}{2}$ hours) Peter had aggravated a small toe blister gained the week before on Mt Arthur.  Lunched at 12:00 just before Kings Hut.  Put on extra pair of socks as my feet were not feeling the best.  At Kings Hut discovered a lemon and fishing line.  Peter mentioned that the Karamea was reputed to offer some of the best trout fishing in NZ so we felt the line would be better left in the Roaring Lion Hut!  The lemon would not keep so we ate it.  Old Kings Hut was full of character.  Built by a prospector around 1932 and used throughout the Depression.  Later, Mr King lived in Wellington (Lower Hutt) but spent summers prospecting his claim.  He died around 1980 and his ashes were scatter around the hut and claim, thereby making the place somewhat mystical.  A photo of the old man in the hut showed an intriguing physiognomy.

After lunch ($\frac{3}{4}$ hour) our speed slackened to a little under stated track times.  The packs were weighing us down.  The pain^[For this trip I was using my original Nelson Trapper frame-pack, with a retrofitted waste-band]!  Initially, I had had twinges in my lower back but fortunately these ceased.  However, my feet were sore (although not blistered) and my left knee and thigh gave some pain.  Fatigue was quite intense by reaching Stone Hut (6$\frac{1}{2}$ hours walking - 16:45).  So much so that a stumble would have been hard to recover from.  Not that I did stumble.  I used Arnica on my knee at Stone Hut but not elsewhere (on me that is!).  Stiffened up badly however.

Interesting botany lessons from Peter, who was also feeling the strain of the pack weight.  Lessons on alternation of the generations helped to relieve, or rather distract from the pain!  It was really quite bad but now, and even at the time, a certain ethereal power seemed to make it all not merely tolerable but rewarding.

Excellent view of Patriarch from just after Kiwi Stream.  Very hot out of the bush, but alas the sun had disappeared behind clouds by the time we reached this hut.  Thus the socks and singlet I rinsed will not dry.  Excellent dinner.

Must brush teeth and tidy up before it gets too dark ...

__06 December__:  
Having crossed Wangpeka Saddle, I have decided to make notes as we go along.  There is so much to write.  Coprosmas have opposite leaves with a stipule between them.  _Griselinia_'s distinguishing feature is its uneven leaf (i.e., where the leaf edge meets the stem is not the same on both sides).  A great view of Nugget Knob from the Saddle, but not one I thought would photograph well.  The damage done by the Murchison Earthquake (1928?^[Actually, it was 1929]) has been apparent all day.  Much more impressive than the views from the Buller road.

Currently we are pawing over a mossy flat looking at insects and tiny flowers through a hand lens, and Peter is photographing.

As yet, although a little stiff, no acute discomfort.  The pack is still heavy, but comfortably so - if that's possible!

Now at Trevor Carter Hut.  Named in memory of an 18 year old hunter who died in 1972 when the hut was built.  Quite what other connection there may be is not stated.  Sandfly Hut could be a more appropriate name.

This hut is built at the base of the Luna Slips (which I photographed earlier with Mt Luna in the distance.  Also tried to get a photo which captured some of the natural rockery beauty of the _Heliochrysum_ spp.  Unfortunately, this latter and the first view of Kendall were on the end of the old film which I think may not have wound on properly).  Anyhow, the hut is built on slip territory and the Karamea River nearby has been partially dammed thus slowing its course and making for some nice swimming holes.  Peter was game, but not I - sandflies too bad!

Arnica on left knee and shoulders.  Everything else OK today.

Saw a couple of paradise ducks at Stone Hut.  And a solitary blue duck, whose call pulled me out of bed last night.  Heard another blue as we neared this hut.

The flowers have been magnificent so far.  Not only the _Heliochrysum_ spp, but many others.  Native iris, and a tiny wee snap-dragon.  Some shrub in the Erica family.  A ranunculid.  Others whose names Peter has told me but which escape me now.

He remarked upon  _Neopanax_ which was trifoliate, with juvenile stage highly digitated.  Also a beautiful green - almost translucent.  I have rarely (maybe never) tramped so slowly as today (almost double track times), but the botanising has made it so enjoyable!

__07 December__  
Lunch - After dinner yesterday we wandered up the slip site behind the hut to look at the colonising plants.  Great walking without a pack!  The main colonising shrub was _Gaultheria_ (the Ericaceae).  Beautifully shaped leaves with red edging in younger group, and covered in creamy bell-like flowers.  Generally only 500mm or so high, but some reaching over a metre.  Obviously capable of growing under poor conditions.  Also present was a prostrate type, and beech seedlings.  Numerous mosses, sedges etc.

This morning we left around 08:00.  There was considerable low cloud on the tops but as expected this cleared around 09:30.  Saw the biggest trout either of us had ever seen.  In the Karamea, just before turning up into the trackless country up Kendall Creek.  Going has been very varied - strolling through open beech forest, struggling through slip damage, bashing through scrubby Coprosomas, rock-hopping by creeks.  Currently heading for a bivvy on the bushline tonight.

Attractive columnar _Rubus_ flowering here - grabbed a photograph.

18:00 - Ridge leading to Kendall Ridge around 5000'^[This was the days of inch to mile maps].  It has been hard yakka up to here and Peter had seen snow earlier so felt it unnecessary to carry water.  Unfortunately, we are still at least 2 hours from the snow.  I am very tired, thirsty and miserable.  I don't think I can make it to the snow as the ridge between looks very fierce.  I know Peter wants to carry on, and thus feel very much of a wet blanket holding him back.  I finally agreed to give it a go, but by then he decided it would be wrong to push me (not that he has).  Hence he has gone for a brief recce to look for water.  I hope this split is the right decision.  In a sense it's OK.  Peter was going to come by himself so going alone looking for water is not too different.  I am, of course, sitting comfortably by the packs.  In a way I hope he finds water.  I am so thirsty now that the sight of Peter returning with two bottles of water would surely gladden my heart!  But then if he doesn't find any it's back the way we came.  This prospect doesn't bring me great joy, but currently is more desirable than going on.  The returning option is unattractive for two reasons: i) it is defeatist and ii) it is very steep and I am not looking forward to going down a slope that was so difficult to come up.

I must remember in future not to set my sights too high with regard to tramping.  There are many magnificent walks to do without pushing myself to the limits.  Here comes Peter now - no water.  So back down the way we came.

__08 December__  
09:00 - Bivvied last night by a creek at about 3000'.  Only flattish spot in the flood-water course so we risked it.  No rain.  This morning much like yesterday morning, with the same promise of a fine day.  Peter has gone on another recce.  We keep getting bluffed out.  Not so bad without a pack (as Peter is now while I wait on a ledge).  Unfortunately it is still misty thus making route finding rather awkward.  This won't lift until ten-ish.

Last night we didn't finish eating until after 21:30, and the sleep was not exactly comfortable.  However, despite the restless sleep I feel better now, but still more daunted than usual.

Coming up passed the waterfall near the bottom yesterday was fascinating.  Solid rock with natural flow-forms sculpted into them.  Also one very nice spa-sized bath.  Very refreshing to dunk one's head into!

Trying to make the base of that waterfall was difficult.  We tried to bash through 3m scrub first.  Hands and knees territory.  This proved to be unsuccessful, but ... we did stumble (literally) on a group of native orchids.  Beautiful modest green.  We retreated and found an easier way.

Bluffed out - back to yesterday's spot.  But this time carrying water!!

10:30 - Now back on top of ridge that we had reached last night before returning.  Took an hour from the creek.  Mist has lifted and the sun is shining brightly.

Coming up we ventured upon a bluff with a scree slope below.  We skirted along underneath this bluff (south west aspect) following a row of mountain buttercups (_Ranunculus insignus_) looking for all the world like someone had planted them there.  Presumably they were following the moisture seeping out of the bluff.

Also in the same spot were tiny flowering _Euphrasia_ (eye bright).  These pretty little flowers - white with a yellow throat and dark filaments looking insect-like - are a root parasite.  Feathery tutu (_Coriaria_) are also fairly common and presently in flower.

Weather possibly packing in - better go.

__09 December__  
10:55 - We have stopped along the track to photograph some orchids.  Back to yesterday ... We were unable to make it further up the ridge without undue anxiety.  The rock is still unstable from the earthquakes.  Even huge boulders (500 lbs?) could give way under hand or foot.  With the steepness of the country in many places a slip would be fatal.  We didn't come for that sort of thrill!  So it was back down, passed the waterfall and flow-forms, down Kendall Creek, and Taraua Tramping Club walk to Thor Hut.  That day our backpacking began a little after eight in the morning and finished a little before eight in the evening.

Whilst sitting atop the ridge we debated our options.  One was to try further up Kendall Creek to get up on top of Kendall Ridge/Herbert Range.  We felt this would preclude a chance of spending much time in the Roaring Lion wilderness area.  Hence we returned and are now headed for the Karamea Bend.

A few other plants I should mention include _Pratia_ (a small white flower which looks a little like it is missing one petal), _Epilobium_ or willow herb which carry tiny white flowers on the end of long ovaries, _Cardamin_ which have Nasturtium-like leaves and develop long seed pods like _Epilobium_.  These pods develop after fertilisation and are not apparent in the flower.  Today we have seen a lovely wee orchid (coloured like commercial varieties but much smaller).  It had an interesting hook mechanism to facilitate insect pollination.

Karamea now a big river with deep and frequent pools of clear water.  We often see huge trout in these pools - four in one pool!

Finished lunch - time to go (13:45).

19:00 - Leslie Hut at Karamea Bend.  Arrived here - flash hut - and quickly went down for a swim and wash.  Lovely and warm with good fresh wind to keep away sandflies and help dry clothes!  Good to feel clean again.

Had some lower back pain and mild sciatica last night and feel it again now.  Must hang upside down a bit.

NZFS have planted a Eucalyptus woodlot here.  A good idea?  Many apparently fine ideas have led to ecological disasters.  What if they seed everywhere?  Why not use manuka or some other native as a woodlot species?

Must mention the _Phylocladus_ (celery pine).  As a tiny seedling these have true podocarp-type leaves or needles.  But as the seedling grows the characteristic celery 'leaf'(really a flattened petiole) develops.  Peter and I saw tiny seedlings with the two 'leaf' styles today.  Only about 50mm high.  Also saw a lovely native broom in flower.  Tiny purple and white flowers.

__10 December__  
14:14 (after lunch) - Resting under a flowering kamahi looking over the Karamea towards some limestone bluffs.  Peter noticed a trout in the pool here so we baited a hook with a centipede and threw it in the pool.  No luck so far which hardly surprises us.  We'll perhaps try again at the Roaring Lion.

Weather so far has been brilliant, but today there is quite a wind which may auger a change.

Have seen lots of animal sign along the Karamea, and actually saw four goats.  Bush is very open - these facts are probably related.

Shortly after leaving Karamea Bend hut we came across some _Equisetum_ and have seen it off and on ever since.  Some stands are very dense and quite pure,  However, getting it out would be a problem.

Crossing the Leslie this morning was not 'lovely and warm' - strange how things change overnight!

Must wind in the line.

__11 December__  
08:04 - Just packing to leave Roaring Lion Hut.  No time for comment; just wanted to note down _Hydrophilis letratorous_ and it to mentioned in this hut regarding testing with a rubber glove not to be touched^[This is as written in the diary, but it doesn't make sense and I could find no reference to _Hydrophilis letratorous_ on the internet].

11:47 (on ridge leading up to Marshall Range) - Another change of plans this morning brings us up here.  We are headed for the Peel Range in the end but may alter plans again.  Roaring Lion Hut has a nice aspect - unfortunately many people chopper in and out.  This sort of thing always leads to an untidy hut.  Sandflies were very bad, but the hut was screened and smelt so much of fly-spray.  Made a lure out of chocolate wrapper but did not catch any trout.  Only tried for a short while however.

RL Hut is in the wilderness area and so is this country northwards.  However, deer and goat sign is so prevalent that this is more modified than many places I have been.  Including Kendall.  Also the number of introduced weed species along the Karamea is disappointing.

Walking to RL Hut was most varied.  Around bluffs, through swamps, bush and tree graveyards, sand like a desert and shingle banks.

__12 December__  
08:25 (Marshall Range above Cavern Creek) - Just packed up the bivvy and about to go.  Uncomfortable last night - also sleeping bag got wet from the dew.  Almost dry now though.

Big day yesterday - left RL Hut about 08:45 and finally arrived at bivvy site 20:15.  Bit of snow up here for water.  Didn't get dark until around 21:30, although with the bright quarter moon (waxing) it didn't really get dark until it set, blood-red, around 03:00.  Sunset over Grange Range was magnificent.

Saw a hare up here.  Also heard a stag and saw a hind in the bush on the way up.  Keas up here, busy all night necessitating a spot of defensive action to prevent bivvy damage.  Also seen a couple of black-backed gulls wheeling around this morning, and yesterday evening.

Quote for yesterday - from Peter - "You can see those squid boats a long way away.  Mind you, they can't be that far or else you couldn't see them."

On our way - almost.  The numerous lakes and tarns in this country are really impressive.  Hundreds of tempting camp sites.  Unfortunately we are getting a little pushed for time and food (reminds me - one loaf of Norths Bread and 250g cheese will do for five lunches at 4$\frac{1}{2}$ slices per lunch.  Second loaf gone moldy now).  Actually lack of time detracts a little from the pleasure.  Towards the end of the afternoon with miles left to go, I get a little despondent.  Peter, however, seems the model of patience and fortitude.

Going now ...

10:45 (upper Cavern Creek) - Things to do at home: make putties, wash sleeping bag and shorts, test fertiliser sacks as bivvy bag, mend boots, polish leather jacket.  As much as anything, I note these down as a remark on my thinking.  My boots, or rather the right one, is falling to pieces.  The nails securing the uppers to the sole are pushing through and jabbing into my foot.  This is less painful than one might expect.  Anyhow, I have removed three, which in addition to those gone earlier, make the sole only loosely attached.  Not much longer to hold out now however.

Just found a low herbaceous Coprosma-type with a little orange berry I associate with the genus.  Peter squeezed the berry to reveal two seeds which he said confirmed it as a Coprosma, although he was surprised it was so soft and herbaceous.  But ... I have just been interrupted.  Peter has discovered the plant to be a _Nertera_!!  The two seed test apparently only works to distinguish between shrubby types of plant.

There has been a particularly prolifically flowering hebe on the tops.  Right in the peak of flowering.  Give it a kick and it sheds petals like snow.

__13 December__  
Early morning (saddle between Mt Prospect and Mt Ranolf at head of Chaffey Creek) - Bivvied here last night.  Set up camp in the mist - rather Peter did while I went off to get water.

Coming down Cavern Creek was slow work.  Not especially difficult (although had it been in flood it would have been impossible!) but slow.  Right at the end it was rather gorged with big boulders interspersed with pools.  Necessitated a brass monkey wade which caused us to fill the gorge with yells!

Made it to the Roaring Lion by about 15:00 and thus began a long slog up through the bush.  Nearer to the top however the way became quite distinct - following a clear ridge, possum line, vegetation survey and hunters' main route into the Roaring Lion from the Cobb.

We made the tops by around 19:30 and reached this site at 20:30.  Never seem to get time to read!

Throughout the trip the bellbirds have been delightful.  More like the chiming of bells than I have heard before.

Another splendid day.  07:50 now - clear up camp, get some more water and go ...

Midday (more or less) - Peter photographing a plant.  We have just come over Ranolf - our first named peak.  The view was incredible.  This side some of the climbing was a little tricky too.  Good fun though.

From Ranolf one can clearly see our trip for yesterday and the day before.  Yesterday, coming down Cavern Creek, two incidents occurred to me.  Once the branch I was standing on gave way and I fell down a hole.  I recovered with my face about 10mm from a bunch of nettle!  Another time, I left to cross the river and gently pushed off from the boulder nearby.  Suddenly I spun a full 360$^\circ$ on one foot placed on a slippery stone.  Again, I regained balance.  Guardian angels busy!

I'm resting in a wee saddle among the vegetable sheep (_Raoulia_).  Very much 'out of this world' these vegetable sheep grouped around on the stones.  As I only have two slides left, words will have to do.

Before leaving the camp this morning I shot down to get more water.  However, there are many tarns and patches of snow about so it was hardly necessary. In fact, we are forcing ourselves to drink more than we want so that our bottles and bellies can be full as we leave each supply.  Who knows where the next supply will be.

Maybe I mentioned it earlier, but going up Kendall Creek (it seems so long ago), I lead us through a rugged slip site and Peter lost his hat.  Now he wares a flour sack that I brought up as a spare billy bag.  With his map/knife belt, boots and putties, dark glasses, zinc cream and flour sack he really looks the part.  Desert king!  Not that I can look like much with a knotted red 'kerchief as a sady-style head cover!

Still haven't decided whether to exit via Tablelands (out tomorrow afternoon) or Cobb (out this afternoon).  Both ourselves and our clothes now very much in need of a wash, despite the bath at Karamea Bend.  Hope our chauffeur can tolerate the smell!

19:30 (Cobb Reservoir, settlement end) - We decided to drop down (steeply) into the Chaffey and walk to Trilobite Hut.  It was our intention to camp there, and walk out along the road tomorrow.  However, we arrived just in time for a lift with a vegetation surveyor to the settlement.  Now we await our ride home.

Walking out today we saw some flowering gentian (did I mention the odd-leaved orchid we saw on the tops?), _Bulbinella_ (Maori onion), bluebells and a small greenish clematis with a glossy green invaginated leaf.

All in all a splendid tramp. __No__ regrets!!.  Perfection ...

## St james Walkway (December 1989)
### Harm tho Seeth, Alisa, Michael and me

__Day 1__:  
The bus was late so we weeded the bark garden around the war memorial.  Alisa felt a bit travel sick on the bus although she didn't complain.  There was a small 4-year-old girl on the bus, and Alisa enjoyed talking and laughing with her.

We finally started our walk around 14:10 (forgot to mention we passed a number of cyclists whilst on the bus, including Ule and Kristin).  The children walked well, although Alisa complained a little of sore shoulders. In fact, she and Michael are getting the Arnica out now!   Some trees had fallen over in the path recently - probably in the storm we had last Friday.  We saw some friendly robins, also rifleman.  Heard long-tailed cuckoo, and possibly shining cuckoo as well.  Also discovered a clump of hooded orchids with their unique pollination mechanism.

Made the hut (Cannibal Gorge) after 4 hours (track time 3$\frac{1}{2}$).  First here, but now (20:00) there are about 3 other parties - 7 or 8 people in all.

__Day 2__:  
Christopher Hut:  Arrived about 15:30 after leaving Cannibal Gorge just before 08:00.  On Harm's suggestion we went down to the Ada River (snow fed) for a bath.  We all felt like we could walk another 100 miles after that!

Dinner is cooking, Alisa is playing the recorder and Harm is entertaining Michael while I write this.

Has been quite a long day today, but the children have managed well.  Some highlights: a bridge called Billy Goat Gruff Bridge, range horses, Michael and Alisa washed their socks and shoes in every creek, Harm taught them to count to ten (zehn) in German, some beautiful rest spots in the sun with magnificent views of the mountains.  Harm carried Michael's pack for about 20 minutes during the day, and I did the same for Alisa.  Somebody had picked some wild gooseberries and left them in the hut so maybe we will have a pudding tonight.

One beautiful day, although there are signs that tomorrow's weather will not be so salubrious.  It snowed here a couple of days before we arrived!

__Day 3__:  
Camping by the Anne River about 2$\frac{1}{2}$ kilometers up from the confluence with the Henry.  Left at 08:00 this morning though I had to go back for Michael's hat.  Arrived here about 16:45.  Lovely spot.

Forgot to mention that Michael and I went to fix the water supply at the last hut and on the way back Michael got stung by a nettle.  "Daddy, that plant bit me!".  Poor chap.

Today has been long and hot and a little tedious.  Seventeen km in all.  Highlights: Michael slipped down a bank almost into the Anne, getting to know William Earl of Kent as we leap-frogged passed each other, sliding down a hill at the camp-site (knicker-bocker breaking or bottom-bruising), finding small trout in the Anne.

Early night tonight (20:00) which __may__ lead to an early start tomorrow.

__Day 4__:  
Wonderful night's sleep.  Good early start - about 08:00.  Intermittent drizzle today with a chilly tail wind.  Highlights: Anne Saddle, dead hare on the path, Michael and Alisa colliding on the path, all of us in Harm's tent at night, Alisa getting to like swing bridges, pole bridge, three huts (Rokeby, Boyle River and Magdeline), mistletoe, wassailing Harm, nice evening meal of kidney beans with pea & ham soup mix added, good pace kept by the children who both carried their packs all the way.  Bed at 20:20.

__Day 5__:  
Out to the road by about 11:00.  Boiled billy and had some soup.  Allan almost passed us - in fact, he did but just noticed us in time and returned.


## Mt Arthur Carpark to Rolling River Junction (December/January 1991/92)
### Alisa, Michael and me

__Useful notes for future reference__  
One canister (190g net) camping gas cooked four meals for three of us.

__Walking times__  

* Mt Arthur carpark - Salisbury Lodge: 11:00 - 15:30 (4$\frac{1}{2}$ hours)
* Salisbury Lodge - Karamea Bend: 09:00 - 15:30 (6$\frac{1}{2}$ hours)
* Karamea Bend - Crow: 09:00 - 14:00 (flooded) (5 hours)
* Crow - Thor: 12:00 - 17:00 (raining) (5 hours)
* Thor - Luna - Helicopter Flat - Stone Creek: 09:00 - 13:30 - 15:40 - 19:40 (rivers high but clear) (about 11 hours)
* Stone Creek - Rolling River: 09:00 - 15:30 (6$\frac{1}{2}$ hours)

Track times on the Wangapeka accurate for us.

__28 December__:  
Lilly and Anne walked with us to the Flora Saddle, but saw no Minpins.  We passed a man finishing lunch at Flora Hut.  He, in turn, passed us later and talked a while.  He was a surveyor and hunting guide in Alaska during their summer and spent the Northern winter down south.  He was going to spend time fishing in the Karamea.

At Gridiron Rock Shelter met DoC staff who told us that the forecast was for rain tomorrow but then fine.  Sounded OK.  Alisa tired a little towards the end of the climb to the Tablelands, and I carried her pack for 15 or 20 minutes.  Then she recovered.  After arriving at Salisbury we rested a short while before going up Sphinx Creek.  The rock after which this creek is named lost its head during the Murchison Earthquake and thus did not look special.  Michael and I both got stung by nettle hidden in the long grass, but not badly.  Mikes was not keen on the cave at the end of the creek - too dark.  However, another before the end on the true right had better limestone structures (although many had been broken) and more light.  In all much more rewarding.

About five others in the hut - including a fisherman from London.  Rice, dehy veges and Maggi soup for dinner.  Quite satisfactory.

__29 December__:  
Low cloud early in the morning, lifted somewhat to reveal Mt Peel and the lower slopes of Mt Arthur around 09:30-10:00 when we were on the Tablelands passed Salisbury.

Fairly long slog of a day to Karamea Bend, but not sure why.  Track reasonably graded and only a little muddy towards the top.  London fisherman passed us early on, but we saw him fishing the Leslie shortly after lunch.

Passed, but did not enter, Spludgeons Rock Shelter (about halfway to Leslie Clearing Hut) and Leslie Clearing Hut.  Reached Karamea Bend Hut and hit out for a bath but it began to rain so decided against it.

An English lady (Lesley) arrived shortly after us - going the opposite way.  And later Jeremy (the fisherman from London).  We told him we had seen him fishing, and he replied that would have been shortly before he fell in.  As the rain had stopped we went for a bath (excluding Michael) - most refreshing.

__30 December__:  
Raining, and has been all night.  Karamea in flood.  Jeremy walked with us today.  For company, safety and to assist in places.  First obstacle occurred when the path went close to the Karamea and was awash with about 3' of water.  No current, but littered with logs and twigs.  Jeremy piggy-backed Michael and I took Alisa.  Met many further obstacles of this nature - some we had to wade, others walk (bush-bash) around.  In a couple of places the track followed flood over-flow channels.  Thus we had to slosh up through the current in 6" - 1' of water.  In one place we came to a loose piece of #8 wire stretched across a slow moving creek.  There proved to be a submerged tree-trunk bridge (about 2' under) associated with this.  I crossed first and saw a huge eel at the far end. I dropped my pack and returned to help Michael.  The children asked what I had seen and I told them. "Oh - there it is!" they cried, and pointed to an even larger eel swimming about my legs.  Jeremy asked me to pick it up so he could look at it better!!  I got Michael across and was turning to help Alisa when Michael inadvertently pulled the wire and thereby unbalanced me.  Thus I was balanced with my feet on the bridge, clinging to the wire, but unable to move.  Finally got back without getting thoroughly soaked.  Shortly before reaching Crow Hut we met a couple of men who told us not to try to reach Venus as a creek between the two huts almost drowned them.  Hence Crow Hut became our destination.

Jeremy managed to get some sort of fire going to dry some of our things.  Particularly Alisa's sleeping bag which had got wet in places as her pack was not water-proof like I expected it to be.  Robert (Alaskan surveyor) joined us later and we whiled away the hours in talking and organised inefficiencies (plus reading 'Dear Enemy').  Saw blue duck (whio) at Crow/Karamea confluence.

__31 December__:  
Further rain during the night, but not in the morning.  The Crow had dropped, and the weather looked to be possibly clearing.  We decided to wait for the rivers to drop before going further.  However, rain set in again and the Crow began to rise.  Stopped again shortly before lunch, so we decided to press on.  Robert stayed at the Crow Hut, but helped us passed the first and worst creek.  Jeremy accompanied us to Venus Hut where a group of guys had just arrived from Thor.  They reported no difficulty so we carried on (in the rain) to Thor.  And indeed, although there were tricky parts it was not as challenging as the Karamea Bend - Crow stretch.

Better fire at Thor - even dried my socks!

__01 January__:  
No fanfare for the New Year. Just more rain last night, but today looks really promising.  Large patches of blue sky.  We all left about the same time, but Jeremy (feeling rather cheated of his fishing) soon got ahead of us.  He would wait at any dangerous spots, but as these never came we did not see him again.

Forded Mars, Apollo and Kendall with no problems.  However, as I wished to save time, we needed to cross the Karamea at Luna.  This presented some difficulty, but I finally found a safe spot.  I crossed with my pack which I dropped and then returned for each of the children in turn.  They walked, me holding them well and carrying their packs.  Mikes was a bit worried, but after that fording he knew he had accomplished something and thoroughly enjoyed all successive crossings (four more of the Karamea before the day finished!).  Rivers still up but the water clear.

Had lunch in Luna Hut and pressed on up the Lost Valley and over the saddle to Helicopter Flat on the Wangapeka Track.  Eager to make up lost time we moved on toward Stone Hut, knowing that we could pitch the tent along the way if necessary.  Although we passed some lovely tent sites, we did make Stone Hut at 3 minutes over track time after already having gone 6$\frac{1}{2}$ - 7 hours.  The children were brilliant!! Eleven and a half hours tramping including two saddles and numerous river crossings (8 substantial, 5 of the Karamea alone!).  And not a word of complaint.

I bathed in the Wangapeka (very __very__ cold) and the children panned unsuccessfully for gold.

Oh yes, we had seen another whio in the upper reaches of the Karamea.

__02 January__:  
Out.  Not much more to say after yesterday.  Good views - hopefully Alisa's photos will turn out.  Less people on the Wangapeka than the Karamea which surprised me.

A great tramp - made much more challenging and exciting due to the rain.  Children did superbly.  Lots of bird life - robins especially.  Fun singing "Good King Wenceslas" - and very appropriate at times.  Also went through the Shepherds' Play a few times!!  Pity about the lack of time for gold panning.  Will try a weekend trip sometime - perhaps to Courthouse Flat.


## Baton/Loveridges (January 1993)
### John Rice and me

__02 January__:  
Left Baton carpark at about 12:00; arrived at Ellis Basin Hut (6 bunks) at 18:00.  Well marked track, but steep.

__03 January__:  
Left at about 08:00, tried to sidle the Twins too high and wasted 2$\frac{1}{2}$ hours.  Arrived at start of Loveridge Ridge around 16:00 (good camp sites in vicinity, about 15-20 minutes towards the Baton).  Followed Loveridge Ridge to peak and down to Loveridge Hut at 18:30 - 19:00 (2 bunks, hard to find and since removed).

__04 January__:  
Left Loveridge Hut at 10:00 and went down poorly marked track but clearly defined ridge to arrive at the Baton River about noon.  Out to carpark around 15:00.

## Heaphy Track (January 1993)
### Alisa, Michael and me

__18 January__:  
Left Brown's carpark at noon, and arrived at Aorere Shelter 16:30, continued to Perry Saddle and arrived there around 18:00.  Moderate to strong westerly blowing cloud and rain over the saddle, and thus decided to stay in the hut.  Very well graded track, pretty straight-forward.  At highest point (Flanagan's 910m) Michael stepped off and up and thus went higher than either of the rest of us.  Alisa forgot the tooth paste.  Everyone had tender feet, but otherwise well.  Time to read some 'Lorna Doone'.

__19 January__:  
Breakfast - What a night! Windy and raining.  Poor ol' Mikes doesn't like that sort of weather much at home!  How many times did he call out "Daddy ... Daddy!"  "Uh?" "What time is it?". Alisa wanted to go to the toilet - __twice__.  "This night will never end" she complained.  But of course it did.  Now we've had breakfast and will head onto Gouland Hut (2 hours) or Saxon (another 1$\frac{1}{2}$ hours) after some more 'Lorna Doone'.  We'll be walking into the wind and the rain, and (I guess) will get pretty cold.  Though the temperature is not low.

Evening - Weather began to clear, with wind dropping and rain ceasing so we departed around 09:30.  In fact, the weather improved to a cloudless evening, though still somewhat breezy (SW) which has now died.  We had the closest view of riflemen that I have ever had.  It was shortly after leaving Perry Saddle Hut whilst walking through a passage in low bush.  A 'family' of five or so of the tiny birds flittered close to the path, almost allowing Michael to touch them.

Made Gouland Hut after 2 hours but stopped only to fill the water bottle, and as it turned out, leave my diary, map and money behind.  At our lunch stop an hour later, I realised my loss when I asked Michael to get the map.  After some deliberation we decided to return and had gone back 15 minutes when we meet Corina (German lady) who said that my map bag was at Gouland and that the family there, who had also been at Perry Hut, were bringing it to Saxon.  Hence we went with Corina to Saxon.

Once at Saxon (1$\frac{1}{2}$ hours) we rested a little then bathed. Corina then went on to Mackay but the others came - including Chris and Diane Bolderston who were dairy farmers from Ashburton and knew Richard (of course!).

Michael asks that I record he spilt soup - which he and Alisa made all without my help or direction while I was talking with Chris - on the floor.  He cleaned it up with no fuss.

Great sunset tonight.

Cribbage tally so far: 1 to me and 1 to Alisa.  I lost my little gold pencil during today's game - hence the pen.

Both tonight and last night we had weka at the hut.  Dragonflies on the track today, and _Drosera_ along the banks.

Track in very good condition so far, but I understand it deteriorates from here.

__20 January__:  
Left Saxon Hut about 09:30 and arrived at Mackay for lunch.  Very pleasant day through Mackay Downs.  Fine weather, but still with a chilly nip in the air.  In fact, there was a frost last night.  Wind has picked up again this evening.

With only three hours walking the day has been relatively uneventful.  Some expansive views South to the Domett Range, but again lousy camp sites around the hut.  At Saxon it would have been a water bed, and here a rubbish tip!

__21 January__:  
Morning - Michael and Alisa are still asleep, it being only around 07:00.  Sunset last night not as magnificent as I remember from twenty years ago but had the same characteristic of beginning after one thought it had ended.  Squid boats on the horizon lit up the sky.

Alisa won another cribbage game, and they paired up in some mysterious hut euchre game to take the honours, though at one stage it looked like they would suffer an ignoble defeat.

Mikes and I, whilst looking for a good camp site (which didn't exist), found a couple of 'graves'.  And also some blue (gentian?^[Probably not, maybe harebells]) flowers.  Mikes fed a _Drosera_ plant some sandfly, but got no thanks!

Should be a reasonable early start today, maybe 08:00.  On to Heaphy Hut - a proper day today.

__22 January__:  
Now at 'The Last Resort' in Karamea.  Went from Mackay Hut to Heaphy which as the first place we could tent.  Then out to following day (i.e. today).  Michael had a bad stomach ache at the end - combination of hunger (as we had a late lunch) and anxiety about the weather (fearing a storm).

## Nydia Track (January/February 1993)
### Alisa, Michael, Lilly, Tao and me

  When EJ walked the Nydia Track  
  Left, right, up we go  
  The sun shone hot upon her back  
  Left, right, up we go
  
  Go up, EJ  
  Right up to the Nydia Saddle  
  Keep on walking  
  Left, right, up we go
  
  (to the tune of "Let My People Go")

__30 January__:  
After 2$\frac{1}2{}$ hours from Motueka arrived at the start at Tennyson Inlet.  Except for the last 12-15km the road was sealed, but the unsealed portion was very rough.  Had lunch before we started and sorted out Tao's pack (such things as three sunhats seemed unnecessary!)

The walk was gazetted as 4 hours, but we took 4$\frac{1}{2}$.  To Ngawhakawhiti Bay was about an hour, and there were a couple of pleasant tent sites there, though water appeared to be scarce.  Nydia Saddle was well graded and the bush, though secondary, was lovely.  Views of the turquoise sea - splendid.

Big kids kept ahead most of the time - waiting every 15 minutes or so far EJ and me to catch up.  EJ did well, and only complained a little after 3 hours or so, when climbing the hot graded path to the Saddle.  However, I carried her for about 5-10 minutes.  Then, after a rest, it was only a short while 'til the top, and she managed the downhill bit well.

Pleasant campsite here.  A couple with a boat and two dogs, and a Swiss couple hiking in.  But plenty of sheltered sites among the kanuka.  Boys are chasing weka.  I don't approve but they can't catch them.

Expect some rain tonight, but hope for fine weather tomorrow.  Boating couple are listening to "Jukebox Saturday Night".

__31 January__:  
Walked around Nydia Bay, almost to Tibbs Cottage for lunch.  Tao has gone on to the cottage while the other three wait here with me - and the sandflies.

Numerous shellfish - mussels, pipis and cockles - all along the coast line.  Unfortunately the toxic algal bloom score prevents us eating any.

__01 February__:  
Out - beautiful weather.  A good trip.

## Pearse Resurgence (7 March 1993)
### Jean and me

Approximately $\frac{1}{2}$ drive to the footbridge from where the track starts.  Initial 40 minutes walking above the river and in the open.  From there one begins the river crossings.  Probably over a dozen before the source is reached.  Total walking time a smidge under 2 hours.  Follow a dry creek off to the left (true right) for 15-20 minutes to arrive at the entrance to the Nettlebed (aptly named) Cave system.

Pleasant day - started about 09:30.  An hour for lunch.  Explored mouth of cave and home again by 16:30.  OK for older two, but river crossings perhaps too much for Lilly for another couple of years or so.

## Mt Owen (16-17 April 1993)
### Me alone

__16 April__:  
Fine settled weather.  Chilly.  Left home at about 09:35 and began walking by 11:30.  Driving time approximately 1$\frac{3}{4}$ hours (10 minutes less to Rolling River Junction) - distance 77km.

Took ridge track to Billies Knob.  Very hot in sunshine.  Meet with bush track after about one hour twenty and continued a short way before lunch.  Too tired to make it to the sunshine!  Feeling much refreshed now though and ready to proceed (although have probably stiffened up).  Very few birds, but _lots_ of wasps making a continuous background hum, although not creating a nuisance.  After a little over $\frac{1}{2}$ hour for lunch, I shall pack up and head on up.  Time 13:20.

Arrived at hut 15:30; i.e., 4 hours after leaving Courthouse Flat which includes the 30 minute lunch break.  I noticed some folk report doing the trip in an incredible 1$\frac{1}{2}$ hours including passing over Billies Knob.  Oh to be so fit.

Didn't notice the old prospector's hut (was meditating) but did note some good camp sites (except for water shortage).  Bivvy site about 10 minutes this side of top of Staircase, under limestone bluffs.  Useful in a pinch.  Track from ridge where it emerges from the bush and top of Staircase could be difficult to follow in poor visibility (need at least 50m, preferably more).  However, this section is relatively short (about 20 minutes).

Hut in magnificent setting.  Ghost Valley quite magical - almost silent: no birds and no running water and no wasps.

Hut book indicates it may be possible to climb Mt Owen tomorrow and return to Courthouse Flat.  May elect to do this if weather (and fitness) permit.

Last sun left hut at 16:50, and Billies Knob about 50 minutes later.

__17 April__:  
Left Hut at 08:15 in relatively windy conditions (southerly) and high cloud.  Reached Mt Owen summit at 10:10 - track fairly easy to follow on a fine day (without snow).  Magnificent views: D'Urville, Tapuae-o-Uenuku, St Arnaud, Kendall and Patriarch, ... Weather still looking fine although thin covering of high cloud developing.  Well worth the effort.  Feel great and at peace.

Back at hut at 11:45 and had lunch.  Tarns south of saddle at top of Hay Paddock represent halfway point to Mt Owen summit.

Left hut at 12:30 and reach here (top of Staircase) an hour later.  Still and hot.  Absolutely beautiful.  Billies Knob looks tempting, but I'll just do it by armchair (or tussock flat).  This is the poorly marked section of the track and lasts about 20 minutes (all going well).  I'll just check the book and map, then continue.

Clear enough if one goes over saddle then into the bush.

Out to car at 15:20.  Legs very tired on down hill bits.  Not very fit!  Highly satisfying tramp.

## Lake Angelus (6-7 November 1993)
### Jens and me

__06 November__:  
Awoke at 05:30 and left home around 06:20.  Arrived at Rotoiti around 08:00 and finally began walking at 08:20.  Weather variable, but rain set in by 14:00.  Hence when we arrived at hut at 15:00 we were fairly wet.  After late lunch and a good rest, we climbed Mt Angelus which took about 1$\frac{1}{2}$ hours (1 hour coming back - scree jumping and skating on the snow).  The Lake is still iced over, although the Hinopouri Tarns were absolutely beautiful - partially iced over, not broken ice but a couple of huge bits floating in the middle of an emerald green (not quite emerald, but still) lake.

__07 November__:  
Slept long but restlessly.  Too hot.  Left hut at 10:30 and reach car at 15:30, after a half hour stop at the ski-field shelter.  Little wind most of the way, but visibility poor.  However, ridge track easy to follow.  Snow conditions good.

Brilliant weekend, but not weather-wise.  Jens made good company.

## Diamond Lake (26-27 November 1993)
### Jean and me

Two hours drive time; 2 hours to Lake Sylvester (lunch at 11:15); 2$\frac{1}{2}$ hours to Diamond Lake via Lake Lillie.  Up to ridge by Mt Lockett (without packs) 1$\frac{1}{2}$ hours up and $\frac{3}{4}$ hour down.  Back via Iron Hill - 6$\frac{1}{2}$ total which included almost an hour for lunch.  Too early for best flowering.

_This is written on Sunday after returning home._  
Jean drove, which trip lasted about 2 hours, but given that we left at around 07:15 this was fine.  It was her father's birthday on the Friday (74) which  must put him at a similar age to my father.

The four-wheel-drive track to Bushline Hut was steeper than I recall, or at least that part which climbed was.  We had an early lunch at the Lake and then climbed up to the flat ridge top to the North where we found the old wheel tracks of the tourist route running E-W along the top.  We followed this to where the ridge turned towards the SW and some cairns marked the track down a grassy lead to the open valley of Iron Stream.  From here there was a clearly marked track through the bush - albeit narrow and steep - to the open ridge.  Following the 4500' contour, we sidled west to Lake Lillie and then dropped through steep open bush to Diamond Lake as the weather was beginning to pack in - hail, but not heavily.

Found a lovely campsite just inside the bush at the SW end of the Lake.  We erected the tent and climbed in before the rain became too heavy - in fact, I recall we even had time for a cuppa.  Jean was tired and beginning to get a headache so she went to bed.  I followed her example, and dozed through an hour of showers.

As the weather had cleared (just as forecast) we had another cuppa and went up the ridge to the North.  Passed some gloriously 'landscaped' hebes and other plants (including speargrass which was one of the many new experiences for Jean!) to a rocky portion.  There was scattered snow on the ridge top and a glorious view particularly to Mt Snowden in the North.

Our route down was further west where a scree slope took us about a third of the way down to the tussock, flaxes, speargrass (easily avoidable) and hebes.  Back at the tent, I put dinner on (real food - potatoes, kumara, green beans, turnip, pumpkin, chicken and burgle wheat flavoured with Maggi's chicken soup), after we'd boiled up for another cuppa and gingernuts.  Then it was sheltering in the tent for the showers had started again.  Dinner was ready around 20:30 - and very nice it was too.

It rained further during the night and Jean cried out - though in my half conscious state I thought it was a dog.  The afternoon rest was very pleasant, but I slept somewhat fitfully that night.  However, my right knee was partly responsible for that.

The sun was a little late coming to us in the morning, but we were able to breakfast at the edge of the Lake in the sun.  Jean noticed a pair of rifleman feeding their young in a nest in a hole about 20' up a beech tree at the Lake's edge.

Jean wisely accepted my offer to carry some of her gear as I had cooked much of what I had been carrying.  At a little after 08:00 we left in brilliantly fine weather and started plodding up to the ridge running SW to the NW end of the Iron Hill Range.  Once on the range, the ridge to point 5356' was real "Sound of Music" country - to steal Jean's description.  However, the passage to Iron Hill and beyond was not so easy and involved sidling round rocky gendarmes and clambering over outcrops.  Not too difficult, or dangerous, but perhaps too arduous for Alisa and Michael at the moment - and potentially difficult route finding in misty weather.  The view, though restricted by cloud in the far distance, was splendid - particularly of the glacial lakes (Lockett especially, but also Lillie and later Iron) and the meandering Cobb River.  Satisfaction level very high.

At the top of Iron Hill there was a scattering of quartz rock - strangly incongruous among the rusty brown/grey conglomerates which prevailed.  We picked our way slowly and steadily South before dropping through a steep and narrow cut to Iron Lake.  Hence along between the Sylvester Lakes and out to the car.  Lunch was had early (11:30) on a rocky platform overlooking Iron Lake.

Magnificent country.  Very satisfying tramp which I have been wanting to do for some time, particularly as it involved some route-finding with no-one more experienced than me to do it.

## Nelson Lakes (1-5 January 1994)
### Alisa, Michael and me

Track times:  
Mt Robert carpark to Speargrass Hut 2$\frac{1}{2}$ hours  
                  to Howard 3 hours  
                  to Rotoroa 3 hours  
Rotoroa to Angelus Hut 6+ hours  
Angelus Hut to Hopeless 4-6 hours

Actual times:  
2$\frac{1}{2}$ hours to Speargrass; and just over 3$\frac{1}{2}$ hours to Howard after a rest of almost an hour at Speargrass Hut.  Further 3$\frac{1}{4}$ hours to Sabine Hut on the edge of Rotoroa.  
Rotoroa to Angelus Hut 5$\frac{1}{2}$ hours

__01 January__:  
Walked to Howard.

__02 January__:  
Tented, in the rain, at Howard last night as the hut was full.  Left there at around 09:00 (in the rain) and arrived here at Sabine Hut after about 3$\frac{1}{4}$ hours (still in the rain).  This hut is now also crowded, but as we were almost first we have right of possession.  Have managed to dry the tent fly, but not much else.

From Speargrass to Howard was fairly muddy - in fact, Alisa went up to her thigh, much to her displeasure.  Also first part of the track from Howard to here was pretty muddy.

Michael spotted a big (about 900mm long) eel lazily looking for a sheltered spot in a tributary of the Howard.  He tried to snatch a picture but we don;t hold much hope.

Michael didn't like today's rainy weather, made him a little disheartened, although I found it most replenishing.  All our pack gear was dry, although I was pretty soaked myself.  Alisa didn't particularly enjoy the latter part of this morning's walk.  Found going downhill in the mud and rain somewhat disconcerting.

Alisa is currently making instant pudding so I'll record a few more notes.  Most people have expressed horror at the weather and also the prospect of the climb to Mt Cedric.  This is unfortunate as it damages the confidence of the troops unduly.  However, we have sufficient food and options to wait here three days for good weather and I am prepared to wait.  Failing better weather we'll just go back the way we came, or out to Rotoroa and try to get to St Arnaud from there.

__03 January__:  
07:30 - Weather still looks unsettled and windy at the tops, although that may be simply early morning (well, morning anyway) cold currents.  We will wait until around 09:00 before making our decision.  At the moment I'm inclined towards waiting here another night.  We sang 'Happy Birthday' to Dad yesterday, as we plodded along in the rain.  I don't guess he heard, but nevertheless we did sing it.  The day before we were singing variations on "Quarter Master's Stores":

  There was mud, mud, good to cool your blood  
  On the track, on the track  
  There was mud, mud, good to cool your blood  
  On the Speargrass walking track
  
  My shoulders are sore, my legs are tired  
  My feet are blistered, my knees are mired  
  And rest is just a memory  
  _The chorus wasn't strictly true at the time but still ..._
  
Other verses told of:

  There were foes, foes, but Michael shot their toes  
        ...     trees, tress, swaying in the breeze  
        ...     roots, roots, fit to trap your boots  
        ...     packs, packs, enough to break your back  
        ...     creeks, creeks, some of them knee-deep  
        ...     rain, rain, driving you insane  
        ...     hikers, hikers, fit as mountain bikers
             
We've heard a few kaka, but not seen any.  However, around this hut the robins appear very tame.  Also, black swans on the Lake, and (I think) scaup.

At Howard Hut there was a very inauspicious looking stream close by from which some people got their water, and we were told to do so.  However, I didn't like the look of it at all, and went a little further to the main river.  Anyhow, for whatever reason, one of the trampers was ill in the night.  He was not too ill in the morning and appeared to be improving.  Others had already left that morning to walk to St Arnaud and I guess notified Park staff.  This fellow seemed to be capable of boxing along out and was happy for us to go on so, somewhat betwixt and between, we did.  I have his phone number, as he has a bivvy bag for sale and lives in Mapua, so I may ring him when we get out again.

When asked if there was anything particular they wanted to say, the Children replied "We want a story", so I don't guess "White Fang" will last the whole trip ...

__04 January__:  
Yesterday morning was promising and by 09:00 we'd had breakfast and decided that it was worth attempting the trip to Angelus via Mt Cedric.  So we packed up and began walking around 09:45.  We had only 1.5l of water to last until we reach the snow, so fortunately it wasn't sweltering hot.

The strategy was to plod slowly up for 10 minutes and rest out packs upon a rock or stump for 30-60 seconds before continuing.  After three such rests we allowed ourselves a couple of swallows of water each.  Hourly we had our scroggen/chocolate ration to accompany the water, and a longer rest.  Michael's pack had lightened as we had eaten some of his food and I had some of his communal stuff (toilet gear).  He managed well, but Alisa began to flag after 30 minutes or so as her pack was still at initial weight.  Thus we re-arranged things - she took my carry mat and I her clothes.  With this new distribution of load we trudged along to arrive at the bush line after climbing 2500' at a little after noon.  The sun was shining and we all felt the wonderful exhilaration of the views.

However,, before we reached the top of Mt Cedric (inaccurately marked on the map) the wind picked up and the mist came in.  Sheltering behind a rock we put on warm clothes and started following the ridge.

Beyond Cedric this ridge appeared pretty awesome, although in fact is was quite straight forward sidling.  However, the poor visibility spooked Michael (fortunately the wind had almost subsided), although the track was still reasonably clear and we could generally see one pole before leaving the other, and always before the other disappeared.

We stopped in a sheltered spot and ate a packet of crispbreads and some cheese.  As we were at the snow (isolated patches) we could drink our fill of water (which wasn't much).  Michael was much better after this and when the clouds lifted with the wind and I could see Hinapouri Tarns and thus realised how close we were his spirits soured.  We quickly dropped towards Angelus Basin and out of the wind and arrived at the hut at 15:15 after 5$\frac{1}{2}$ hours (5 hours walking which is a remarkably good speed).

We are currently sharing the Hut with seven others: two Americans, two Germans, two Kiwis and a Londoner.  The weather is inclement: strong winds, lashing occasional rain, permanent cloud and periodic thunder and lightning.  Thus, our carefully laid plans have come to naught.  We all read, write diaries, play cards or dice, and eat.  However, the company is good and the hut comfortable so we experience no discomfort.

__05 January__;  
Whilst awaiting a bar meal at the Alpine Lodge, I'll add a little more to this diary.  Last night was wild and stormy - in fact, Michael woke me last night asking "Daddy, will we ever see Mummy and Lilly again?".  I thought he was talking in his sleep but he wasn't.  Michael insists that I record that he "thrashed us in a game of euchre".  Anyhow, here comes the meal ...

__06 January__:  
Having just finished breakfast and Alisa and Michael still being in bed (08:00) I'll finish this.  We walked out along the Cascade Track as conditions were too poor for Robert Ridge - strong winds from the NE bringing some rain and hail and continuing cloud.  Hukere Creek was clear but up - waterfalls thundered down into the valley swelling the creek.  It was truly awesome.  No particularly difficult river crossings compared to Karamea, although when we crossed Hukere at the waterfall I choose to take the children's packs and hold hands as a slip would have been fatal (or at least nasty).  This portion of the track took 3$\frac{1}{2}$ hours with Alisa suffering some knee pain.  From Hukere/Travers junction to Coldwater Hut was about 1$\frac{1}{2}$ hours and along the Lake (which was up about 0.6 - 1m) a further 2 hours before heading along Paddy's Track to the Robert carpark ($\frac{3}{4}$ hour).  We didn't have a proper lunch stop, but choose instead to have two-hourly munches on crispbread and cheese to keep us going.  These intermittent 'semi-lunches' are included in the above times.

Must try the trip to Angelus via Speargrass Hut (track time 3+3 = 6 hours) and out via Hopeless sometime.  Lake Angelus is a wonderful place, and well worth revisiting and revisiting.

## Asbestos Cottage (28-29 January 1994)
### Alisa, Lilly and me

__28 January__:  
Left home at 10:30 and arrived at the track start 3km past the power house at 11:45 after driving through a herd of bulls at the base of the hill before the Rat Trap.  We had lunch before starting and made the open-cast mine after about 1$\frac{1}{2}$ hours.  Much debris was to be seen rusting away and the mine itself. Quite fascinating.  On to Asbestos Cottage - an old smokey hut with no suitable tent site so after a brief rest we returned to the mine village site and pitch our tent.  I prepared our jelly and popped some corn before putting on dinner proper.  It'll be ready shortly, and afterwards we might further explore the mine before story and bed.

Low cloud has persisted all day (hence no Michael) but it isn't too cold.  Quite pleasant really.  Very little wind and only a few sandflies.

Had some problems with Elizabeth being bolshy (and me being unnecessarily short) at dinner time.  This is almost a nightly ritual at home but I was not expecting it whilst tramping.  She'll have to learn to do as requested before coming again.  After dinner, however, she was very good.  Jelly and stewed dried apple with a sprinkling of scroggen made an excellent desert.

We did explore the mine after dinner, and before pudding.  Quite interesting, particularly the asbestos - some fibres upwards of 3cm.

__29 January__:  
This tent is very spacious compared to my other one - worth the extra weight.  Lilly woke once during the night disturbed by the birdsong.  However, there were no possums but whether this was due to our efforts to wee all around the tent site is anybody's guess.  I did see fresh possum scat yesterday.

I have been up since 06:45.  Besides mixing the milk for breakfast I have done little - just read and now write this diary.  It's now 08:10 and the sun has just struck us.  The sky is cloudless, but the girls still sleep.  Perhaps it was the bath they had last night?  I wasn't comfortable as the ground under me was too uneven.  Stirrings in the tent - I suspect Alisa and Lilly will soon be up.

### Lake Angelus (11-12 March 1994)
### Jean and me

__11 March__:  
I awoke at 05:00 and was at Jean's by a little after 06:00, as planned.  We went in her car via Brightwater, Belgrove, Rees Saddle etc - distance to Yellow House about 107km.  Jean felt this was shorter than going up the valley, and from her place I think she may be correct.

I cannot remember when we started from the Mt Robert carpark - sometime around 08:00.  Just before we left  falcon came in and landed in a beech tree above us.  This was quite a charge for the beginning of the day.  The mist came, lifting from the valleys, as we climbed which generally enhanced rather than obscured the view.  We made it to the hut after about 5$\frac{1}{2}$ hours.  After a short rest and cuppa we set off to climb Mt Angelus.  This took us a similar time to what it did Jens and me.  There was, of course, no snow other than handfuls in places on the south side of the mountain.

Dinner of chicken and veges with jelly and apple to _precede_ it was pleasant.  We had had a bath in the Lake  upon returning from the mountain and felt we deserved a good meal.  "Mon Cheri" chocolates to finish.

__12 March__:  
Neither of us slept particularly well - I was getting a sore throat and Jean was pre-menstrual.  Thus we both felt a little seedy all day.  However, it was a wonderful day.  I have dotted our approximate route on the map down to the Speargrass Track.  I remember the bridge is actually only 100m from the hut.  We choose our route in order to get the view to the west of the ridge leading to Pt 5625'.  The tussock/snow-grass was wonderful to walk on.  I suspect many trampers follow the Robert Ridge Trail in order to descend the scree on the true right of Speargrass Creek.  This would certainly be fun although probably less suited to our moods on the day.

Jean struggled against headaches and reduced awareness.  I think this must have been a strain for her, though she never seemed to loose her sense of humour.  Even when she finally went heavily over on her right ankle in the tussock and Sphagnum swamp.  Mind you, her language was pretty basic then!  Arnica, bandage and rescue remedy, and then I carried her pack for 20 minutes or so as she regained confidence.  It was then only a short distance to the track, which was delightfully restful walking through beech forest.  This took us around 6 hours walking.

This round trip would be very suitable for Alisa and Michael for a weekend though Michael might not like the bit through the trackless beech.  However, that only lasts about $\frac{1}{2}$ hour.

## Inland Pack Track (1-5 April 1994: Easter)
### Rice/Moores, Alisa, Michael, Elisabeth and me

__01 April__:  
We arose and ground the wheat to start the dough for the hot-cross buns.  As this was rising, the older two children gathered their things together while I collected the necessary clothing for Elizabeth and me, and the communal equipment.  As usual on such expeditions, Elizabeth and I planned to sleep in separate sheet bags, but under my unzipped sleeping bag.  This has worked well in the past, and again worked well on this trip, and saves taking an extra sleeping bag.

We left around 10:30 and easily made Murchison on under a quarter of a tank of gas - which was as well as it was the first re-fueling place that was open.  We had no proper lunch, but nibbled on crackers, apples, and \$250 cookies.  After a couple of brief stops we finally arrived at the DoC motor camp in Punakaiki around 15:00.  We pitch our tents (total charge \$13, being \$7 per adult and \$2 per child), and then walked to the blow-holes, watching surfers on the way.  After checking for information regarding the Inland Pack Track, and buying a useless route guide for 35 cents, we investigated the blow-holes which were okay, but not desperately spectacular being two hours past high tide.  A Japanese girl from a tour party of young girls wished to pose with us (arms around Alisa and Michael) for the inevitable photograph.  We natives obviously fascinated them!

John, Lois and family arrived around 17:00 and we ate the buns, before preparing a late dinner.

__02 April__:  
We finally dismantled camp and got on the road by around 10:45.  We drove to the Fox River and left Lois there with most of the children, while John, Michael and I went to the end of the Bullock Creek road in order to leave John's car there for our exit.  We returned to Fox River at around lunchtime, but walked in for about 15 minutes in order to find a nicer place to eat lunch.

About an hour after lunch we arrived at the Fox River Caves, which we just poked into.  Rather than retracing our steps for half an hour to cross the river further down-stream, we headed straight down from the caves to the river and crossed there.  However, although the track down was fairly obvious, a track up to the main track was not obvious.  I did a quick scout to find a suitable path, while John investigated the possibility of following the river on up to the Ballroom Overhand.  I readily found the main track, after about three minutes scramble through supple-jack and nei-nei.  However, with our packs on this climb took us over half an hour of hard yakka!  Although Elizabeth found it easy enough as she had no pack.

Once at the track it was easy going to the Ballroom Overhang/Dilemma Creek junction.  Here we crossed the Fox River, and followed it up - crossing it a further six times to reach the Overhang.  This impressive campsite was somewhat dirty, but otherwise very pleasant.  I pitched tent, and went for a bathe in the river, but could persuade no-one else to join me.  It was very pleasant, however.

__03 April__:  
During the night Lois' pack, which she left outside, was torn and some scroggin and bread taken by a possum.

We had had some rain walking in, and perhaps some more during the night, but not much.  The other people (about 8) camping in the Ballroom left in the morning, but the weather looked a little dubious to us, so we decided to stay.  Further rain fell during the morning, and then the wind began to gather.  We figured it might blow in fairly cold and unpleasant so we decided to leave.  However, by the time we had packed and had lunch the Fox River had begun to rise, and after three crossings John and I went on alone.  One and a half crossings later we decided that we would not take our children through rivers so high and returned hurriedly to the Overhang, as the river was rising noticeably.

Back at the Overhand, we marked the river height which proved that we had left at the worst possible time, as it didn't come up any further, and after a few hours began to drop.  I began slicing kindling for a fire, while John hurled large rocks on hunks of timber to break them into suitably sized pieces.  This nicely passed the time until dinner, which was had around the fire.

__04 April__:  
Easter Monday, and the Fox River was clear and down again so we began our tramp out.  The adults wanted to go to Bullock Creek via Dilemma Creek, but at least some of the children wanted to go straight out.  However, we decided to follow Dilemma Creek through the gorge with towering limestone bluffs on both sides.  We crossed the Fox seven times, the Dilemma a further 25 or so, before branching off and following Fossil Creek.  This flowed through mixed podocarp/beech forest hanging with lichen.  Absolutely beautiful, and so different to Nelson.  I am told we splashed across Fossil Creek about 30 times, after which we headed across the hills through beech forest towards Bullock Creek.

During this part of the tramp, I had to carry Lilly for two short periods, more to keep her spirits up than anything.  Much of the time I walked with Emlyn and Lilly, singing to keep us going.  During the river walking, John had walked in front with his two boys, me next with Lilly and Michael, and finally Lois with Alisa and Hania.  At lunch, we were treated to the world premiere performance of "The Life Cycle of the Frog" - an opera for three male voices devised and performed by John, Emlyn and Adrian.

Bullock Creek came after a period of kaihikatea and rush/Sphagnum swamp, and was in an area of private farmland.  It was our last river crossing, being about twenty minutes from the car.  The journey back was eased as Lois, Emlyn, Hania and Alisa got a ride while the rest of us were away getting the other vehicle, which saved a second trip up the torturous road.  The tramp had taken around 5$\frac{1}{2}$ hours walking time, with an hour or so stop for lunch.

We arrived back at the blow-holes around high tide which proved great, as they were putting on a splendid display.  I bumped into Dallas Winch from the Mount whilst watching the main blow-hole.

__05 April__;  
This day we went to Truman's beach for lunch, where the children played in the surf, and collected more wonderful pebbles.  We finally left for home around 14:15 and arrived back at about 18:00 - after a brief stop at Lyall.  From there to home was about 160km - more than one would want to do in a weekend.  Although it would perhaps justify a long weekend's outing.

In all, the trip was a tremendous success.  The weather was good - a little rain to add spice and interest, but not enough to create undue discomfort.  Mild temperatures, and clear skies at night.  For myself, I found the extra adults with whom to share the decisions and responsibilities very welcome.  And the children seemed to get along great - with Alisa and Hania (Bunyip) forming a close partnership, and Michael and Adrian doing likewise.  We have resolved to meet again sometime - hopefully in the not too distant future.

## Mt Owen (23-25 April 1994: ANZAC weekend)
### Peter Sharples, Alisa and me

_I write this weeks after the event (11 May) and thus some of the details may be unreliable._

__23 April__:  
Alisa led the way up through the bush and accomplished the climb with admirable fortitude in about 5 hours or so.  We were thrilled to see 3-5 kaka feeding in a beech tree on the way up through the bush.  We met snow at the burnt clearing and from then until our return seemed to follow the tracks of a hare.

Alisa found the Prospector's Hut, but I wouldn't think it usable even in a pinch - although there is a pleasant flat spot for a tent if one could get water.

At the hut (six bunks, dual-burner gas cooker, pot belly stove but little wood available as it is above the bush-line) we enjoyed warmth while the fire was going but the condensation froze inside during the night; wonderful meals including steam pudding, nacho chips and cheese sauce; cards with one game to me, one to Peter and none to Alisa, although she came second both times so I guess we were equal on points; and comfort, once we put the mattresses on the floor.

__24 April__:  
We didn't actually get up Mt Owen as, in the snow, we rapidly lost the cairned route through the karst.  However, we had a wonderful day walking through the snow (up to knee-deep on me), and climbed Sentinel Hill.  Peter tested the ice on the tarns.  It held his weight until he decided to get off in a hurry and put his foot through.  No real damage done as the day was fine and still.

The Creek to the north of the Railway Embankment was filling as we watched, which made an intriguing tinkling sound as the water slowly edged forward (about 300mm/sec) to make a brook on the previously dry creek bed.

__25 April__:  
We shared the hut with an extremely poorly equipped couple.  I heard kiwi (great spotted female) but was too tired to get up and look for it/them.

On the way out we made a detour up to the ridge leading to the top of Billies Knob (about 1$\frac{1}{2}$ hours up and 1 hour down).  Alisa tired about $\frac{2}{3}$ of the way up, but when I offered to wait with her, she perked up and reached the top easily.  Well worth it, as this innocent rounded knob (as viewed from the north) falls away dramatically with sheer rocky bluffs to the south.  Gives one the willies it does.

Alisa led the way down and on to the carpark, via the ridge.  She managed the downhill with great agility which was the result of renewed confidence.

A fine trip.  Wonderful in the snow with the fine weather.

## Mole Tops and Moss Pass (30 July - 2 August 1994)
### John and me

__30 July__:  
Left home at 06:30 and met John at Rotoroa at 08:00.  Had bad problems with the car missing.  In fact, it stalled going up the Hope Saddle and I thought that may be it.  However, I got there.

We tried to contact Mr Simpson to check he would be available to take us down the Lake on Tuesday, but had to be contented with a note.  Took John's car to Matakitaki Lodge, over 4 water courses (3 with concrete) that would have been impassable after rain.  This took about 45 minutes.  So we finally started at around 10:30 and followed the valley route (rather than the ridge track) to Mole Hut which was a nice tidy 4 bunk shelter with no cooker or heater.  From there it was over Mole Saddle through semi-soft snow (John being 25-30kg heavier frequently stepped through but I was generally OK).  Here the ice axe came in handy.  The route down Bull Creek was no longer maintained by DoC and was a little tricky to follow.  We finally got down to the D'Urville at 18:00 - dusk.

Three hours of night tramping, during which time the batteries from my lamp died (I had spare) and John's light developed faulty connections (he's fixing it now).  Finally we made it to Morgan's hut - 10$\frac{1}{2}$ hours tramping with insufficient food stops! Anyhow, although very weary, I was never down.

__31 July__:  
Today has been easy. Three hours from Morgan's to Ella. In summer, a trip to Mole Hut and exploring the Mole Tops would be excellent.

We never made it to Moss Pass - John was developing a cold.

_Some vital statistics_:  
Road end to Mole Hut was in the order of 2-3 hours, although neither John nor I can remember now  
Morgan's Hut to Ella: 2-2$\frac{1}{2}$ hours when light  
Ella to footbridge at the base of Moss Pass: about 1 hour  
Morgan's Hut to Lake Rotoroa: 2$\frac{1}{2}$ hours (no bridge over the D'Urville)  
Manaaki Whenua pier to Sabine: 2$\frac{1}{2}$-3 hours(considerable distance up the Sabine to the bridge over a lovely gorge)

All tracks in good repair (except Bull Creek, which is no longer maintained).

Morgan's Hut: a cast iron log fire in one section, but nothing in the other.  No gas.  
Ella Hut: wood range in each section, one quite good.  No gas.  
Sabine Hut:  Pot belly.  No gas.

Lake Rotoroa Water Taxi: Craig and Kerry Simpson (03)523 9199.  \$50 or \$20 per person, whichever is the greatest.

## Salisbury Lodge (26-27 August 1994)
### Jean, Melanie, Alisa and me

__26 August__:  
Jean arrived with Alisa and Melanie around 09:15 and we got away about 15 minutes later in Jean's car.  We started walking at around 10:30 and had lunch at the Upper Gridiron Shelter (at about noon).  After a leisurely tramp via - or rather detouring to - the Salisbury Rock Shelter we arrived at the hut at about 15:00.  There were isolated patches of snow.

Jean was unwell (tension headache) but accompanied us to the end of Sphinx Creek.  It was quite different with a large shallow pond before the cave entrance preventing access.

Dinner was delightful.  Pasta with leek sauce and coleslaw, followed by boysenberry steam pudding with cream.  We played a seemingly endless game of hearts until after 22:00.  Then bed.  Salisbury Hut has about 20 bunks, 4 gas rings, and 2 gas heaters.

__27 August__  
Left on Saturday at 08:30 and made the open ridge leading to Gordon's Pyramid about an hour+ later.  There was snow from here for almost all of the remainder of the day.  Generally held our weight and allowed for easy walking.  The wind was brisk and cold until after lunch which was had about $\frac{3}{4}$ hour passed the summit of the Pyramid.

Rather than follow the poles direct to the Arthur Ridge we elected to try to reach Mt Arthur summit by the western route and then complete the round trip down the standard route.  Earlier Jean and I had noted that this was unlikely to be possible for us, but footsteps of others encouraged us to try.  In the event, we turned back.  I was quite comfortable with my ice-axe, and possibly would have boxed on without one - but not happily.  As no-one else had an ice-axe we decided (somewhat reluctantly) to return and follow the poles.  In fact, we took various shortcuts and had lots of fun (and experience) in the snow.  Melanie and Alisa both had their confidence shaken a bit by the forced retreat.  However, I expect that the experience was good for all.  I had fun glissading, tumbling and practicing self-arrest.  Was gratified with that, but had to try the slope again!

We finally returned to the carpark at about 17:50 - tired but, for myself, very pleased with the trip.

## Welcome Flat (6-8 September 1994)
### Rice/Moores, Alisa, Michael, Lilly and me

__Inwards__:  
Left car at 09:55 and reached the hut at 17:30.  Drizzle most of the day, becoming quite heavy towards the end (making the hot-pools particularly welcome).

__Outwards__:  
Left at 10:15 and reached the car at 17:00.  Fine weather.

__Hut__:  
Plenty of sleeping room for about 40 people.  Sleeping upstairs, cooking and eating downstairs.  Coal supplied for pot-belly.  Would be crowded with 20 people, as would the hot-pools.

## Speargrass Hut (15-16 October 1994)
### Jean, Jamie, Alisa and me

_No notes_.

## Moss Pass (22-24 October 1994)
### John and me

__22 October__:  
Water taxi dropped us at Sabine Hut at about 09:00 and we lunched at a nice wee spot about half an hour short of Forks Hut at around 12:30. After an hour and a half for lunch, we moved on and made the Blue Lake Hut at about 17:30.  Blue Lake Hut has 16 bunks and a Forester burner.  The sun was still on the Lake so I had a bathe (with snow coming down to the edge of the Lake).  Many avalanches down to the river - some blocking the track.  Maybe too much snow for Moss Pass, but will check it out tomorrow.

__23 October__:  
Left hut at 07:30 and started up towards the Pass. Unfortunately, the snow was too soft and sugary to hold our weight once the sun was on it.  Also the sun started avalanches so after climbing a little over half way we decided to return and poke up to Lake Constance which was ice and snow covered.  Lovely relaxing day.  John's turn for a bathe today.

__24 October__:  
Had to leave early to make our appointment with the water taxi at 15:30.  Weather has been perfect.

## Tonga Beach - Marahau (31 December 1994 - 1 January 1995)
### Rice/Moores, Alisa, Michael and me

__31 December__:  
Lois and the children caught 'The Excalibur' at Kaiteriteri (\$23 adults, children half price) while John and drove (with David Fletcher and his brother Paul) to Marahau.  David and Paul took my car, and John and I jogged in to catch the boat at Coquille Bay (\$18 each).  However, the jogging was unnecessary as e had a 15 minute await.

The boat took us to Tonga Beach, with a detour to the island to look at the seals. We also saw a blue penguin bobbing in the water.

We lunched at Tonga, before boxing on to Bark Bay about an hour away.  There were no really appropriate campsites for our 4 tents until we reached Torrent Bay, although above Frenchman's Bay we could have set up a couple of tents (albeit without a ready water supply).

Thus we camped at Torrent Bay and were regaled by the New Year chatter of a bunch of middle-aged yachties.  However, although sometimes noisy they were not obnoxious.  Michael, in fooling around on the beach, jabbed a twig deep into his leg at the bottom of his right calf, and Adrian playing with Michael cut his (Adrian) heel.  Thus we had call for the first aid kits.

__01 January__:  
The track (high tide) from Torrent Bay to the Anchorage turn-off seemed to wind on forever.  However, we had a lovely rest at Cleopatra's Pool with its water slide, and a leisurely dam-building lunch at Stillwell Bay.  After collecting some kia moana at Tinline, we finally reached Marahau at 18:00.  Two hours after the appointed time to meet David and Paul.  As they were 1$\frac{1}{2}$ hours late themselves this turned out to be fine.

Each day had about 4$\frac{1}{2}$ hours walking (excluding lunch, but including brief rests).

## Diamond Lake (3-6 January 1995)
### Rice/Moores, Alisa and me

__03 January__:  
Left home shortly before 11:00 and dropped David and Paul in Motueka, actually left them at the kindergarten.  Alisa and I picked up a couple of members of Alf's Imperial Army just outside Motueka and took them to the Cobb turn-off.  The road had not improved and was no better for the extra traffic.

We lunched at the look-out and finally started walking at 14:00.  Some squally and very cold rain had blustered in during lunch and threatened again at the turn to Bushline Hut.  Hence we settled in for the night at the Hut.

__05 January__:  
Yesterday was brilliant weather and we made it to Diamond Lake via Lake Lillie (where we had lunch and I swam) after three hours walking.  John and I went for a walk to Lake Lockett while Alisa and Emlyn made a cheese cake.  The other children threw rocks and Lois (hopefully) relaxed.

It is now after 08:00 and only John and I are up.  It promises to be another scorcher today.

Out over Iron Hill and camped at Lake Sylvester.

## Mt Sommers (May 1995)
### Rice/Moores, Alisa, Michael and me

_No notes_.

## Balloon Hut (6-8 July 1995)
### Jean, Jamie, Cheryl, Melanie, Tim, Alisa and me

__06 July__:  
Left home around 09:15, but there was an excessive delay at the carpark whilst 'Team Mazda' (2 mums and 2 boys) got ready.  'Team Subaru' (Melanie, Alisa and I) stopped at Flora to remove some wool and put on some leggings against the rain.  However, this turned into a long rest when 'Team Mazda' arrived.

Lunch was at the Upper Gridiron Hut where we met Brian Renwick and his two boys.  Wondered on to Growler Shelter where 'Team Subaru' had a long wait for Tim, the 'Team Mazda' representative bringing news that Jamie had twisted his ankle.  I went back and in a little way saw him limping up the track with Jean coming behind carrying his pack.  However, after a short rest he was off - limping exaggeratedly.  As we did not catch him, I suspect the limp disappeared as soon as he was out of sight.

We got to Salisbury around 15:30, wet from the fain and fairly cold.  Melanie made us hot soup, and Cheryl was keen to go on - though I felt (and still do) that it was a crazy idea.  So we went through the snow (aerial and on the ground) to arrive at Balloon at 17:45 as it was getting dark.  Very wet, and pretty cold.  There was another couple in the hut - poor folk!

__07 July__:  
Today we have hardly ventured forth, except to dip for water and go to the toilet.  The snow is falling pretty steadily, with occasional flurries being swirled about by the wind.  Alisa has been doing a sterling job running a Chinese laundry to dry out the clothes.  The packs and rain coats, which we left outside as they were too snowy to bring in, froze over-night.  It's now about 14:00 and Alisa has just about got everything dry.  However, the inside of the hut is heavy with condensation.

Cheryl almost didn't make it to the Hut last night, but Melanie was a real marvel - getting dinner ready and all.  The boys were pretty hopeless though.

Balloon Hut: a gas heater, 4 gas burners, 2 tiers of 'Maori' bunks to sleep about 16.

__11 July__:  
Finally choppered out at about 15:00.

## Mole Tops (not sure when)
### Me alone (I think)

From home to Matakitaki Lodge: about 2+ hours  
Lodge to Mole Shelter (4 bunks): 4 hours  
Shelter to the Tops: 2-3 hours.

Could thus travel to the Lodge on Friday night.  Saturday go to the shelter, leave packs and explore the tops.  Be back home by 14:00 on Sunday.

## Three peaks (3 January 1996)
### Jo and me

Winter Peak - Mt Arthur - Gordon's Pyramid - Clouston's Mine - Flora and out.  
Left the carpark at 08:15 and returned at 17:30.


